# Generated by Django 5.0.6 on 2024-07-15 22:23

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg'])])),
                ('video', models.URLField(blank=True, max_length=500, null=True, verbose_name='Video Url')),
                ('title_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title De')),
                ('subtitle_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle De')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Description De')),
                ('content_de', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content De')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title En')),
                ('subtitle_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle En')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description En')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content En')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title De')),
                ('description_de', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description De')),
                ('content_de', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content De')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title En')),
                ('description_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description En')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content En')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(max_length=100)),
                ('subtitle_de', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=100)),
                ('subtitle_en', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg'])])),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg'])], verbose_name='Image')),
                ('title_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title De')),
                ('description_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description De')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title En')),
                ('description_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='DescriptionEn')),
                ('content_de', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content En')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('-updated',),
                'managed': True,
            },
        ),
    ]
