# Generated by Django 5.0.6 on 2024-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_branch_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.CharField(blank=True, default='FBF-Hagen', max_length=100, null=True, verbose_name='Author'),
        ),
    ]
