# Generated by Django 5.0.6 on 2024-07-15 22:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content En'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content De'),
        ),
    ]
