# Generated by Django 5.0.6 on 2024-07-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_project_content_en_alter_project_content_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description En'),
        ),
    ]
