# Generated by Django 5.0.6 on 2024-07-15 23:42

import django.core.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[None, 50], upload_to='partner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg'])], verbose_name='Image'),
        ),
    ]
