# Generated by Django 5.0.6 on 2024-07-16 01:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_social_alter_footercontact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer_de', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Disclaimer De')),
                ('disclaimer_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Disclaimer En')),
                ('privacy_de', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Privacy Policy De')),
                ('privacy_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Privacy Policy En')),
            ],
            options={
                'verbose_name': 'Disclaimer',
                'verbose_name_plural': 'Disclaimers',
                'managed': True,
            },
        ),
    ]
