# Generated by Django 5.0.6 on 2024-07-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_disclaimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='Image')),
                ('title_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title De')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title En')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'managed': True,
            },
        ),
    ]
