# Generated by Django 5.0.6 on 2024-07-16 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg'])], verbose_name='Image')),
                ('title_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title De')),
                ('description_de', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description De')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title En')),
                ('description_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description En')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('id',),
                'managed': True,
            },
        ),
    ]
